ex19_Api_and_Parameter_Implementations_from_Different_Providers/ex19_Api_and_Parameter_Implementations_from_Different_Providers.cpp
ex19_Api_and_Parameter_Implementations_from_Different_Providers/ex19_parameter_impl_by_abc.cpp
