#-------------------------------------------------------------------------------
include $(DEPTH)/Makefile.common

#-------------------------------------------------------------------------------
## Concatenate all header/lib include paths
INCS+=$(CCI_EXAMPLES_INC)

LIBS=$(LIB_DIR) \
     $(GS_CCI_LIB) \
     $(SYSTEMC_LIB)

#-------------------------------------------------------------------------------
## Standard build rules
all: $(EXE)

#--------------------------------------- 
#$(GS_CCI):
#	$(MAKE) -C $(DEPTH) -f Makefile.gs_cci

#--------------------------------------- 
#$(EXE): $(OBJS) $(GS_CCI)
$(EXE): $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS) 2>&1 | c++filt
	test -x $@

#-------------------------------------------------------------------------------
## Supplementary rules
Makefile.deps:
	$(CXX) $(CFLAGS) $(INCS) -M $(SRCS) >> $@

announce:
	@if  ( test ! -d $(FLAG_BATCH) ); \
	 	then echo; echo "$(EXE):"; echo; \
	 fi
	
check: announce $(EXE)
	@./$(EXE) $(EXE_ARGS) > run.log 2 >&1
	@diff --strip-trailing-cr ./run.log ../reports/expected.log > diff.log 2>&1;\
	if [ -s diff.log ]; then echo "***ERROR:"; cat diff.log; else echo "OK"; fi

run: announce $(EXE)
	@./$(EXE) $(EXE_ARGS)

clean: 
	-rm -f $(OBJS) diff.log run.log

cleanbuild: clean all

cleanall: clean
	-rm -f $(EXE) Makefile.deps core

#-------------------------------------------------------------------------------
## Add dependency rules for the files being compiled
-include Makefile.deps

