DEPTH=../../build-unix
SRCS_WOPATH=testbench.cpp
SRCS=$(addprefix ../src/,$(SRCS_WOPATH))
OBJS=$(SRCS:.cpp=.o)
INC_DIR=-I../inc
EXE=parameter_value_change_callbacks.x

include $(DEPTH)/Makefile.config

