DEPTH=../../build-unix
SRCS_WOPATH=testbench.cpp 
SRCS=$(addprefix ../src/,$(SRCS_WOPATH))
OBJS=$(SRCS:.cpp=.o)
INC_DIR=-I../inc
EXE=fully_supported_data_type_param.x

include $(DEPTH)/Makefile.config

