#-------------------------------------------------------------------------------
include $(DEPTH)/Makefile.common

#-------------------------------------------------------------------------------
## Concatenate all header/lib include paths
INCS+=$(CCI_EXAMPLES_INC)

LIBS=$(LIB_DIR) \
     $(GS_CCI_LIB) \
     $(SYSTEMC_LIB)

#-- Store current working directory
CWD=$(shell pwd)
#-------------------------------------------------------------------------------
## Standard build rules
all: $(EXE)

#--------------------------------------- 
$(GS_CCI):
	cd $(DEPTH) && make -f Makefile.gs_cci && \
	cd $(CWD) && make

#--------------------------------------- 
$(EXE): $(OBJS) $(GS_CCI)
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS) 2>&1 | c++filt

#-------------------------------------------------------------------------------
## Supplementary rules
Makefile.deps:
	$(CXX) $(CFLAGS) $(INCS) -M $(SRCS) >> $@

announce:
	@if  ( test ! -d $(FLAG_BATCH) ); \
	 	then echo; echo "$(EXE):"; echo; \
	 fi
	
check: announce $(EXE)
	@$(EXE) > run.log
	@diff ./run.log ../reports/expected.log > diff.log 2>&1;\
	if [ -s diff.log ]; then echo "***ERROR:"; cat diff.log; else echo "OK"; fi

run: announce $(EXE)
	@./$(EXE) $(EXE_ARGS)

clean: 
	-rm $(OBJS) diff.log run.log

cleanbuild: clean all

cleanall: clean
	-rm $(EXE) Makefile.deps core

#-------------------------------------------------------------------------------
## Add dependency rules for the files being compiled
include Makefile.deps

