## ****************************************************************************
##
##  Licensed to Accellera Systems Initiative Inc. (Accellera) under one or
##  more contributor license agreements.  See the NOTICE file distributed
##  with this work for additional information regarding copyright ownership.
##  Accellera licenses this file to you under the Apache License, Version 2.0
##  (the "License"); you may not use this file except in compliance with the
##  License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
##  implied.  See the License for the specific language governing
##  permissions and limitations under the License.
##
## ****************************************************************************

## guess config from environment

## Variable that points to SystemC installation path
#SYSTEMC_HOME?=
#JSON_HOME=
#CCI_HOME?=
#BOOST_HOME?=

## Select the target architecture
#TARGET_ARCH = linux

## Select the architecture suffix, if necessary
#ARCH_SUFFIX = -$(TARGET_ARCH)

## How to instruct the dynamic linker to locate the SystemC library
#LDFLAG_RPATH = -Wl,-rpath=

# default compiler flags
FLAGS_COMMON = -g -Wall
FLAGS_STRICT = -pedantic -Wno-long-long

#TODO: More strict tests
#FLAGS_WERROR = -Werror

# combined flags
#EXAMPLES_CXXFLAGS = $(FLAGS_COMMON) $(FLAGS_STRICT) $(FLAGS_WERROR)

# Additional preprocessor symbols
#EXAMPLES_DEFINES =

# Common utility files for examples
#EXAMPLES_INC_DIR = $(CCI_HOME)/examples/cci/common/inc

# Explicit location of the CCI headers
#CCI_INC_DIR = $(CCI_HOME)/include

# Explicit location if the CCI library
#CCI_LIB_DIR = $(CCI_HOME)/lib$(ARCH_SUFFIX)

# Run with valgrind
#VALGRIND=valgrind --log-file-exactly=valgrind.log
