name: visualstudio

on: [push, pull_request]

jobs:
  build:
    name: "Build"
    strategy:
      fail-fast: false
      matrix:
        systemc_version: [3.0.0, 3.0.1]

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Cache SystemC ${{matrix.systemc_version}}
      id: cache-SystemC
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}\tmp\systemc-${{matrix.systemc_version}}
        key: visualstudio-systemc-${{matrix.systemc_version}}

    - name: Setup SystemC
      if: steps.cache-SystemC.outputs.cache-hit != 'true'
      env:
        SYSTEMC_URL: "https://github.com/accellera-official/systemc/archive/refs/tags"
      run: |
        choco install wget
        mkdir -p ${{github.workspace}}\tmp
        cd ${{github.workspace}}\tmp
        wget ${{env.SYSTEMC_URL}}/${{matrix.systemc_version}}.tar.gz
        tar -xvf ${{matrix.systemc_version}}.tar.gz
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        msbuild .\msvc16\cci.sln `
            /m `
            /p:WindowsTargetPlatformVersion=10 `
            /p:PlatformToolset=v143 `
            /p:SYSTEMC_HOME="${{github.workspace}}\tmp\systemc-${{matrix.systemc_version}}" `
            /p:SYSTEMC_MSVC="${{github.workspace}}\tmp\systemc-${{matrix.systemc_version}}\msvc16" `
            /p:RAPIDJSON_HOME="${{github.workspace}}\configuration\src\rapidjson" `
            /p:CPlusPlusLanguageStandard=c++17 `
            /p:Configuration=Release `
            /p:Platform=x64
